services:
  api:
    restart: always
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "8000:8000"
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      wait-for-qdrant:
        condition: service_completed_successfully

  wait-for-qdrant:
      image: jwilder/dockerize
      networks:
        - app-net
      command: -wait tcp://qdrant:6333 -timeout 30s -wait-retry-interval 2s && sleep 2

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: on-failure
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Q1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - app-net

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker-start:
    build: .
    command: python -m app.workers.call_start_worker
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file: .env
    restart: on-failure

  worker-end:
    build: .
    command: python -m app.workers.call_end_worker
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file: .env
    restart: on-failure

  worker-record:
    build: .
    command: python -m app.workers.record_worker
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      wait-for-qdrant:
        condition: service_completed_successfully
    env_file: .env
    restart: on-failure
    volumes:
      - ./data/recordings:/app/data/recordings

  worker-sms:
    build: .
    command: python -m app.workers.sms_worker
    networks:
      - app-net
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file: .env
    restart: on-failure

networks:
  app-net:
    driver: bridge