services:
  api:
    restart: always
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "80:8000"
    depends_on:
      - kafka
      - mongodb

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Q1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  worker-start:
    build: .
    command: python -m app.workers.call_start_worker
    depends_on:
      - kafka
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:29092
    restart: always

  worker-end:
    build: .
    command: python -m app.workers.call_end_worker
    depends_on:
      - kafka
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:29092
    restart: always

  worker-record:
    build: .
    command: python -m app.workers.record_worker
    depends_on:
      - kafka
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:29092
    restart: always

  worker-sms:
    build: .
    command: python -m app.workers.sms_worker
    depends_on:
      - kafka
    env_file: .env
    environment:
      - KAFKA_BROKER=kafka:29092
    restart: always